---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/EmptyBlock:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  RightTrim:
    enabled: true
    enforced_style: "-"
  # conflicts with prettier
  ClosingErbTagIndent:
    enabled: false
  # conflicts with prettier
  SelfClosingTag:
    enabled: false
  # conflicts with prettier
  SpaceInHtmlTag:
    enabled: false
