require:
  - rubocop-capybara
  - rubocop-rails

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
