require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
